# Only expose ports for the apps that will accept API calls

services:
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: npm run start:dev reservations
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: npm run start:dev auth
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app
  
  payments:
    build:
      context: .
      dockerfile: ./apps/payments/Dockerfile
      target: development
    command: npm run start:dev payments
    volumes:
      - .:/usr/src/app

  notifications:
    build:
      context: .
      dockerfile: ./apps/notifications/Dockerfile
      target: development
    command: npm run start:dev notifications
    volumes:
      - .:/usr/src/app
  
  mongo:
    image: mongo
    ports:
      - 27017:27017

  rabbitmq:
    image: rabbitmq
    ports:
      - 5672:5672